### ISSUE TITLE
Slides for intro to content mining

### ISSUE THREAD

**Issue by jcmolloy** [ContentMine/SciDataCon2014#1]
Slidedeck describing content mining and potential projects, ideally drawing examples from other open sources. Upload to Wikimedia Commons.

**Comment by jcmolloy** [comment]
@punkish do you have something for this from a previous talk?
@Treblesteph @petermr any links to previous presentations/documentation?

**Comment by punkish** [comment]
I don't have a generic intro slide deck for TDM (mine focuses on legal
issues), but if y'all don't have one, I could put one together.

On Tue, Oct 28, 2014 at 6:00 PM, Jenny Molloy notifications@github.com
wrote:

> @punkish https://github.com/punkish do you have something for this from
> a previous talk?
> @Treblesteph https://github.com/Treblesteph @petermr
> https://github.com/petermr any links to previous
> presentations/documentation?
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/ContentMine/SciDataCon2014/issues/1#issuecomment-60747577
> .

## 

Puneet Kishor
Manager, Science and Data Policy
Creative Commons

**Comment by jcmolloy** [comment]
@punkish If you could that would be great. Happy to work on this together during our planning afternoon as well.
